name: Lint & Static scan
on: 
  push:
    branches:
      - dev
      - master
      - release/*
    pull_request:
      branches:
        - dev
        - master

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python security check using Bandit
        uses: Krocodial/bandit-report-artifacts@master
        with:
          project_path: '.'
          ignore_failure: 'false'
          security_level: 'l'
          security_confidence: 'i'
